# Generated by Django 5.0.6 on 2024-06-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ach',
            name='difficulty',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='ach',
            name='reward',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
