# Generated by Django 5.0.6 on 2024-08-04 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@default.com', max_length=254, unique=True, verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='The token used for the session.', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the session was created.')),
                ('is_online', models.BooleanField(default=False, help_text='Is user online via this session.', verbose_name='online')),
                ('user', models.ForeignKey(help_text='The user associated with this active session.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Active Session',
                'verbose_name_plural': 'Active Sessions',
            },
        ),
    ]
